In [1]:
import cvxpy as cvx
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

def solve_theta(G):
    n = G.shape[0]
    X = cvx.Variable((n, n), symmetric=True)

    constraints = [X >> 0]  # X is positive semidefinite
    constraints.append(cvx.trace(X) == 1)  # Diagonal entries are 1
    for i in range(n):
        for j in range(n):
            if G[i, j] == 1 and i != j:
                constraints.append(X[i, j] == 0)  # Non-edges have zero entries

    objective = cvx.Maximize(cvx.sum(X))
    problem = cvx.Problem(objective, constraints)
    problem.solve()

    return problem.value

def cycle_adjacency(n,k):
    G = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(1,k):
            G[i, (i + j) % n] = 1
            G[(i + j) % n, i] = 1
    return G

# G is Petersen graph adjacency matrix
# G = np.array([[0,1,0,0,1,1,0,0,0,0],
#               [1,0,1,0,0,0,1,0,0,0],
#               [0,1,0,1,0,0,0,1,0,0],
#               [0,0,1,0,1,0,0,0,1,0],
#               [1,0,0,1,0,0,0,0,0,1],
#               [1,0,0,0,0,0,0,1,1,0],
#               [0,1,0,0,0,0,0,0,1,1],
#               [0,0,1,0,0,1,0,0,0,1],
#               [0,0,0,1,0,1,1,0,0,0],
#               [0,0,0,0,1,0,1,1,0,0]])

#G is complete graph adjacency matrix of 7 nodes
# G = np.array([[0,1,1,1,1,1,1],
#               [1,0,1,1,1,1,1],
#               [1,1,0,1,1,1,1],
#               [1,1,1,0,1,1,1],
#               [1,1,1,1,0,1,1],
#               [1,1,1,1,1,0,1],
#               [1,1,1,1,1,1,0]])

# G is cycle graph C11 adjacency matrix
# G is adjacency matrix of the inverse of the Grötzsch graph
G = np.array([[0,1,0,1,0,1,0,1,0,1,0],
              [1,0,0,1,1,0,1,0,1,1,0],
              [0,0,0,0,1,1,1,1,1,1,1],
              [1,1,0,0,0,1,1,0,1,0,1],
              [0,1,1,0,0,0,1,1,1,1,1],
              [1,0,1,1,0,0,0,1,1,0,1],
              [0,1,1,1,1,0,0,0,1,1,1],
              [1,0,1,0,1,1,0,0,0,1,1],
              [0,1,1,1,1,1,1,0,0,0,1],
              [1,1,1,0,1,0,1,1,0,0,0],
              [0,0,1,1,1,1,1,1,1,0,0]])

#n = 9
print("Lovász theta function value for G:", solve_theta(G))

# test = np.sqrt(5)
# for k in range(3,10):
#     G = cycle_adjacency(2*k+1, 2)
#     n = G.shape[0]
#     theta_value = solve_theta(G)
#     test = test*(1+2/(2*k-1))
#     print(f"Lovász theta function value for n={2*k+1}:", theta_value)
#     print(f"Trying the function", test)

# for i in range(100):
#     b = np.random.randint(2, 5)
#     a = np.random.randint(2*b+1, 11)
#     gcd_ab = np.gcd(a, b)
#     b = int(b/gcd_ab)
#     a = int(a/gcd_ab)
#     q = np.random.randint(2, 5)
#     p = np.random.randint(2*q+1, 11)
#     gcd_pq = np.gcd(p, q)
#     q = int(q/gcd_pq)
#     p = int(p/gcd_pq)
#     G = cycle_adjacency(a, b)
#     H = cycle_adjacency(p, q)
#     #Calculate gcd of a*p and b*q
#     gcd_ap_bq = np.gcd(a*p, b*q)
#     print("a=", a, "b=", b, "p=", p, "q=", q, "gcd_ap_bq=", gcd_ap_bq)
#     I = cycle_adjacency(int(a*p/gcd_ap_bq), int(b*q/gcd_ap_bq))
#     theta_G = solve_theta(G)
#     theta_H = solve_theta(H)
#     theta_I = solve_theta(I)
#     print(f"Lovász theta function value for G with {a}/{b}:", theta_G)
#     print(f"Lovász theta function value for H with {p}/{q}:", theta_H)
#     print(f"Product of theta values: {theta_G * theta_H}, Expected value for I: {theta_I}")

# if n % 2 == 0:
#     print("Expected value: ", n/2)
# else:    
#     print("Expected value: ", (n*np.cos(np.pi/n))/(1+np.cos(np.pi/n))) 

# print("Lower bound ", np.sqrt(n*(n-1)/4))

# # Drawing the graph G, not the adjacency matrix
# nx.draw(nx.from_numpy_array(G))
# plt.show()

# for i in range(1,20):
#     theta_value = (n*np.cos(np.pi/n))/(1+np.cos(np.pi/n))
#     print(i, " ", theta_value**i, " ", np.round(theta_value**i)**(1/i))


Lovász theta function value for G: 2.3997084213926483


In [4]:
import numpy as np
import math
from tqdm import tqdm

d = 5
n = 367
# d = 5
# n = 5
# coeffs = np.array(
#         [[a, s - a] for s in range(1, n) for a in range(s + 1)],
#         dtype=np.int64,
#     )
coeffs = np.array(
        [[a, a] for a in range(1,n)],
        dtype=np.int64,
    )
# coeffs = np.delete(coeffs, np.where((coeffs[:, 0] == 0) & (coeffs[:, 1] == 0)), axis = 0)
q = [147,184]
if (math.gcd(q[0],q[1])==1):
    q_array = np.zeros((2, d), dtype=np.int64)
    for j in range(2):
        q_array[j] = np.array([q[j] ** i for i in range(d)], dtype=np.int64)

    # Linear combination for each coefficient pair:
    # t = a*q_array[0] + b*q_array[1]
    t_array = coeffs @ q_array

print(len(t_array), len(t_array)**(1/d))
print(t_array%n)


366 3.256088624772286
[[  2 331  48 184 124]
 [  4 295  96   1 248]
 [  6 259 144 185   5]
 ...
 [361 108 223 182 362]
 [363  72 271 366 119]
 [365  36 319 183 243]]


In [5]:
q = 11
d = 4
n = 366  # Example value for n
q_array = np.array([q**i for i in range(d)])
# Vectorized: multiply q_array by all t values at once
t_array = q_array * np.arange(1, n)[:, np.newaxis]
t_array = np.mod(t_array, n)
t_array = np.minimum(t_array, n - t_array)
# Vectorized min of max: find max along each row, then min across rows
k_plus = t_array.max(axis=1).min() 
print(k_plus)
print(n/k_plus)
print((q**d)%n)

33
11.090909090909092
1


In [ ]:
import math

for p in range(5, 30):
    for q in range(2, p//2):
        if (math.gcd(p,q)==1):
            G = cycle_adjacency(p, q)
            theta_value = solve_theta(G)
            G = cycle_adjacency(p+q, q)
            theta_value2 = solve_theta(G)
            print(f"Lovász theta function value for {p+q}/{q}:", theta_value2, " for {p}/{q}:", theta_value, " difference:", theta_value2-theta_value)

Lovász theta function value for 9/2: 4.360081464121727  for {p}/{q}: 3.3176667225344074  difference: 1.0424147415873195
Lovász theta function value for 11/3: 3.4517824879795302  for {p}/{q}: 2.3431461217675267  difference: 1.1086363662120036
Lovász theta function value for 11/2: 5.3863178662997235  for {p}/{q}: 4.360081464121727  difference: 1.0262364021779966
Lovász theta function value for 13/3: 4.201151807871214  for {p}/{q}: 3.1671833476405955  difference: 1.0339684602306183
Lovász theta function value for 13/2: 6.404225857542523  for {p}/{q}: 5.3863178662997235  difference: 1.017907991242799
Lovász theta function value for 14/3: 4.505530738785658  for {p}/{q}: 3.4517824879795302  difference: 1.0537482508061276
Lovász theta function value for 15/4: 3.529418216892074  for {p}/{q}: 2.4082211496060992  difference: 1.1211970672859746
Lovász theta function value for 17/5: 3.2134208238013624  for {p}/{q}: 2.1435935390102276  difference: 1.0698272847911348
Lovász theta function value for 

In [3]:
10//4

2